### ISSUE TITLE
how to find previous test runs?

### ISSUE THREAD

**Issue by warn4n** [Cognifide/aet#139]
Sorry this is probably a silly question... a couple of us have installed using the basic setup with vagrant on our locals.  Is there a URL we can hit to see the latest reports, to find them without having to use the maven output? If I've closed my terminal I find myself kicking off a new run just to see the report. 

Probably be less of an issue if we get a real install and get it running from Jenkins, etc.

**Comment by Skejven** [comment]
Hi @warn4n ,
There are couple of ways to access the latest report of AET.
First of them is to access an url that you get from the maven console output. As you will see it contains 3 request parameters: `company`, `project` and `correlationId`. These 3 parameters uniquely identifies a report. However, you can use `suite` parameter with the name of a suite (that you defined in the XML `<suite>` tag) instead of `correlationId`. The idea is similar to the REST API described [in AET Wiki](https://github.com/Cognifide/aet/wiki/RestAPI#get-metadata-by-suite-name).

So, for example if your report has address:
`http://localhost:8181/report/report.html?company=aet&project=aet&correlationId=aet-main-1234567890` 
(that points to a concrete version of a report) you can use:
`http://localhost:8181/report/report.html?company=aet&project=aet&suite=main`
to access always the latest report.

Another way is [listing all suites available in the system](https://github.com/Cognifide/aet/wiki/RestAPI#gets-list-of-all-suites-in-system). Please mind that this is more developer than end-user tool.

Using some CI integration like Jenkins or Bamboo is also a good idea.
Hope that helps you.

**Comment by wiiitek** [comment]
I have added your question to FAQ:
https://github.com/Cognifide/aet/wiki/FAQ#37-how-to-get-the-latest-report-for-the-aet-test-suite

**Comment by warn4n** [comment]
thanks!!
