### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by AxelHo** [Cognifide/aet#36]
Hi,
i tried my best to install the  aet.
The wiki pages are different (maybe older) than the Readme here:
https://github.com/Cognifide/aet/tree/master/vagrant

After a lot of problems i was able to log in via putty. 
I can open http://192.168.123.100/report.html#/suite with chrome.
I see a message "Failed to load metadata!" .
In my opnion i should now create a suite file inside my virtual machine, is this right?
I ask, because there is no maven installed in the VM?

Can you please advice me through the next steps in detail.
Are the wiki pages upto date?
Thanks in advance

**Comment by Skejven** [comment]
Hi @AxelHo ,
Thank you for the question.
Vagrant Readme page focuses only at vagrant running related topics. If you want to start using AET as a tool please visit our [AET Wiki](https://github.com/Cognifide/aet/wiki/). You may find especially interesting chapter [AET In 10 Minutes](https://github.com/Cognifide/aet/wiki/AETIn10Minutes) where idea of using AET is described in a short form.

As I understand you have installed AET on VM already. Next thing you want to do is probably [running AET tests](https://github.com/Cognifide/aet/wiki/RunningSuite).

After running the test you may see the report. The link you provided:
`http://192.168.123.100/report.html#/suite` is a link to the report webapplication, but you have to add the context in order to display a report from the tests (parameters `company`, `project`, `correlationId`). 
This link will be available after [running the tests](https://github.com/Cognifide/aet/wiki/RunningSuite) - you will find `redirect.html` file in the `target` folder. This is the correct link to AET report.

Let us know if you have further problems.
Thank you.

**Comment by AxelHo** [comment]
thank you,
just recieved my first report :-)
