### ISSUE TITLE
Using "variables" in AET suit

### ISSUE THREAD

**Issue by tostermis3** [Cognifide/aet#540]
**Describe the solution you'd like**
In some cases user could use few same steps in aet's suite i.e

```
<open/>
<wait-for-image-completion css="#logo"/>
<click css="#logo"/>
```
The idea is instead above can use just:
`<var1>`

**Additional context**
In my project I used ENTITY for huge _javascript command_

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE variables [
	<!ENTITY var1 "Fuction.setValue(.......]
	]>
```

**And after I can use**

`			<executejavascript cmd="&var1;"/>`

To call this value every time is neccessary. Will be great when I can use one markup then sequence of 5 every time.

**Comment by Skejven** [comment]
While the idea of re-using parts of the suite is very noble, I don't think that implementing variables feature into XML is a good idea.
You can try some kind of XML templating, so that the final XML file is combined by some tool before sending it to AET.
You can find example in the [AET integration tests](https://github.com/Cognifide/aet/tree/master/integration-tests/test-suite) module. We make use of two maven plugins there: `maven-resources-plugin` and `xml-maven-plugin`.

I'm sure there are plenty of tools in many languages that will help you combining the final XML and user variables.

**Comment by tostermis3** [comment]
Ok, thank you for the answer. I'll try then those solution
